on:
  push:
    branches:
      - main

env:
  SECRET_NAME: mytestsecret2
  PROJECT_ID: ${{ secrets.GCE_PROJECT_ID }}
  GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
  GCE_INSTANCE_ZONE: ${{ secrets.GCE_INSTANCE_ZONE }}
  
jobs:
  read_secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_TOKEN }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Add GCloud Beta
      run: |
        yes | gcloud components install beta

    - name: Read secret from GCP Secret Manager
      run: |
        secret=$(gcloud beta secrets versions access latest --secret=$SECRET_NAME)
        echo "::set-env name=SECRET_VAR::$secret"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Use secret
      run: |
          echo "Secret value is: $SECRET_VAR  "
          echo $PROJECT_ID
          echo $GCE_INSTANCE
      
    - name: Call a Bash Script
      run: |- 
        gcloud compute instances add-metadata $GCE_INSTANCE \
          --zone "$GCE_INSTANCE_ZONE" \
          --metadata=starup-script=${GITHUB_WORKSPACE}/startup.sh
